version: 2.6.{build}-alpha
pull_requests:
  do_not_increment_build_number: true
branches:
  only:
  - master
  - develop
configuration: Release
assembly_info:
  patch: true
  file: '**\AssemblyInfo.*'
  assembly_version: '{version}'
  assembly_file_version: '{version}'
  assembly_informational_version: '{version}'
install:
- choco install msbuild.communitytasks -y
before_build:
  - nuget restore source/DD4T.Model.sln
build:
  project: build.msbuild
  verbosity: normal
artifacts:
- path: build/package/**/*.nupkg
  name: NuGet Package
- path: build/package/**/*.zip
  name: Zip Archive
notifications:
  - provider: Slack
    auth_token:
      secure: sPqYbVki+502+OjRT+o3eITyiG8UDZ0Fu4M1fejZxs3O6OKtYu9JCNS9Ssw3/XjL
    channel: development
skip_commits:
  message: /\[nobuild\]/
deploy:
- provider: NuGet
  api_key:
    secure: 6k8EpxxJJcCdjoG0icjAkMkbMZuF9JBRK9tekp2fu7gmWqBn7LGvGleT095VcZ6t
  artifact: /.*\.nupkg/
  on:
    branch: develop
